### ISSUE TITLE
Error: cannot find 'sun' while searching for 'almanac.sun.set.raw'

### ISSUE THREAD

**Issue by trasher** [steepleian/WX-HWS#1]
**Describe the bug**
A python error occurs on cron:
```
Jun 15 22:05:47 domopi weewx[3240]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Jun 15 22:05:47 domopi weewx[3240]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/w34skin/w34stats.php.tmpl
Jun 15 22:05:47 domopi weewx[3240]: cheetahgenerator: **** Reason: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jun 15 22:05:47 domopi weewx[3240]: ****  Traceback (most recent call last):
Jun 15 22:05:47 domopi weewx[3240]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Jun 15 22:05:47 domopi weewx[3240]: ****      fd.write(str(compiled_template))
Jun 15 22:05:47 domopi weewx[3240]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Jun 15 22:05:47 domopi weewx[3240]: ****      rc = getattr(self, mainMethName)()
Jun 15 22:05:47 domopi weewx[3240]: ****    File "_etc_weewx_skins_w34skin_w34stats_php_tmpl.py", line 2558, in respond
Jun 15 22:05:47 domopi weewx[3240]: ****  NotFound: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jun 15 22:05:47 domopi weewx[3240]: cheetahgenerator: Generated 3 files for report w34skinReport in 3.86 seconds
```

**Additional context**
I'm using weewx 3.9.1 installed from `apt-get` on the raspberry, and wx-hws up to date master clone.

**Comment by steepleian** [comment]
Can you check that almanac.py is correctly installed.

**Comment by trasher** [comment]
The file is present and it is located in `/usr/share/weewx/weewx/almanac.py`.

**Comment by trasher** [comment]
One precision: currently, this is the only error that is generated, but my instance is not working at all, it seems it miss data (but I may have misinstalled it - this is a remote setup, not the most simple to achieve as far as I've seen).

I wonder if missing expected data could not be the cause of the error; but I do not know what to check exactly... All I can say is that the weewx static pages are still correctly generated, generated files are not empty.

**Comment by pchaves1** [comment]
I've got the same problem.

**Comment by steepleian** [comment]
try another pull of w34stats.php.tmpl

I just updated this file in the repository

**Comment by trasher** [comment]
The issue is still present after updating the skin, and restarted weewx :/

**Comment by steepleian** [comment]
Can you confirm your WeeWX version please.

**Comment by trasher** [comment]
```
pi@domopi:~ $ weewxd --version
3.9.1
```

**Comment by steepleian** [comment]
Can you try something for me please? Can you install PyePhem.
https://rhodesmill.org/pyephem/

This is not normally necessary to do but it may help.

**Comment by pchaves1** [comment]
got the latest w34stats.php.tmpl and now i have another error:

Jun 16 12:25:49 WeeWX weewx[8724]: cheetahgenerator: Generate failed with exception '<type 'exceptions.UnicodeDecodeError'>'
Jun 16 12:25:49 WeeWX weewx[8724]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/w34skin/w34stats.php.tmpl
Jun 16 12:25:49 WeeWX weewx[8724]: cheetahgenerator: **** Reason: 'ascii' codec can't decode byte 0xc2 in position 1504: ordinal not in range(128)
Jun 16 12:25:49 WeeWX weewx[8724]: ****  Traceback (most recent call last):
Jun 16 12:25:49 WeeWX weewx[8724]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 330, in generate
Jun 16 12:25:49 WeeWX weewx[8724]: ****      filtersLib=weewx.cheetahgenerator)
Jun 16 12:25:49 WeeWX weewx[8724]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
Jun 16 12:25:49 WeeWX weewx[8724]: ****      self._compile(source, file, compilerSettings=compilerSettings)
Jun 16 12:25:49 WeeWX weewx[8724]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
Jun 16 12:25:49 WeeWX weewx[8724]: ****      keepRefToGeneratedCode=True)
Jun 16 12:25:49 WeeWX weewx[8724]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 740, in compile
Jun 16 12:25:49 WeeWX weewx[8724]: ****      settings=(compilerSettings or {}))
Jun 16 12:25:49 WeeWX weewx[8724]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1579, in __init__
Jun 16 12:25:49 WeeWX weewx[8724]: ****      source = unicode(source)
Jun 16 12:25:49 WeeWX weewx[8724]: ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1504: ordinal not in range(128)
Jun 16 12:25:49 WeeWX weewx[8724]: cheetahgenerator: Generated 3 files for report w34skinReport in 0.53 seconds

**Comment by steepleian** [comment]
Ok, I am travelling at the moment. When I get back I will do a clean install of WeeWX and the template on a spare RasberryPi to see if I can eliminate these errors.

**Comment by trasher** [comment]
@steepleian installing PyePhem (`apt-get install python-ephem` give me the 3.7.6.0) solved the python error; thank you very much :)

**Comment by steepleian** [comment]
I am glad that it solved the problem, but confused that it required
PyePhem. I need to investigate further.

**Comment by pchaves1** [comment]
installing python-ephem and rolled back to previous w34stats.php.tmpl, solved the python error.
thank you very much :)

**Comment by trasher** [comment]
> I am glad that it solved the problem, but confused that it required PyePhem. I need to investigate further.

That's why I did not close this issue. Feel free to ping me if I can be of help. I'll try to get all the rest working as expected.

Again, thanks for your help, and also for your projet! I hope I'll be able to get a working setup shortly :p

**Comment by bgrattan3** [comment]
Ian,
I haven’t updated my files for several weeks but adding python-ephem cleared up several things. The temp scales are still off but an update will probably fix that. Thanks
Bob

**Comment by steepleian** [comment]
Added PyePhem to install process
