### ISSUE TITLE
edit w34stats.php

### ISSUE THREAD

**Issue by Mikkel1955** [steepleian/WX-HWS#2]
At the top of the file is a set of headers. I tried to past them here but I did it wrong. This causes index.php to generate an extra set of headers, and cause the browser to have the wrong title in the tab heading.
The fix is to delete everything before <?php

**Comment by Mikkel1955** [comment]
`<!DOCTYPE` HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" `"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`
`<html` xmlns="http://www.w3.org/1999/xhtml">
  `<head` profile="http://www.w3.org/2005/10/profile">
    `<meta` http-equiv="Content-Type" content="text/html; charset=utf-8" />
    `<title>FOUR` CLAYDONS Current Weather Conditions</title>
    `<link` rel="stylesheet" type="text/css" href="weewx.css"/>
    `<link` rel="icon" type="image/png" href="favicon.ico" />

OK - this is the extra header.

**Comment by steepleian** [comment]
w34stats.php removed from repository as it is automatically generated every archive cycle.

**Comment by Mikkel1955** [comment]
My mistake it is /copy_files_inside_to_skins_Standard or Seasons_folder/w34stats.php.tmpl that needs fixing.

**Comment by steepleian** [comment]
Sorry I used my own index.php instead of a generic one.
