### ISSUE TITLE
WiFi Logger working

### ISSUE THREAD

**Issue by mullinp** [steepleian/WX-HWS#2]
I am currently using a Davis Vantage with an WiFi logger.  I have the logger setup to FTP directly to my site. I installed your version and pointed to my data file and it seems to be working fairly well. 

Http://www.kennettweather.com/PWS
Data file is http://www.kennettweather.com/template/update/realtime.txt

This is the logger I’m using:
http://wifilogger.net/

Thanks for your hard work on this!

**Comment by steepleian** [comment]
Thanks mullinp
