### ISSUE TITLE
Information/graph cards not changing color

### ISSUE THREAD

**Issue by exatobg** [steepleian/WX-HWS#3]
**Describe the bug**
Just colors not switching

**To Reproduce**
Set a default theme color in the admin panel afterwards just go to the index page select the other color from the menu, the information/graph cards still keep the default theme color.

**Expected behavior**
Probably the colors to switch when the theme color gets switched

**Picture**
![Capture](https://user-images.githubusercontent.com/36187127/61053445-36e88080-a3f6-11e9-8622-fa3820adf707.PNG)

**Comment by steepleian** [comment]
Hi,

Yes that is correct. The menu setting only controls the mode of the
dashboard.

**Comment by exatobg** [comment]
Hello,

That was a quick reply, i guess then everything is working properly.
