### ISSUE TITLE
Webcam setup

### ISSUE THREAD

**Issue by Mikkel1955** [steepleian/WX-HWS#5]
easyweathersetup.php lets you set the webcam. The information is stored in $webcamurl in settings1.php, but that doesn't do anything. You need to edit cam.php manually instead. Maybe we could change cam.php to use something like:

`<img` `src="<?php` echo $webcamurl;?>" alt="weathercam" class="webcamlarge">
 
instead of:

`<img`  `src="cam.jpg?version=<?php` echo filemtime("http://www.winterman.org.uk/image1.jpg");?>" alt="weathercam" class="webcamlarge">

**Comment by Mikkel1955** [comment]
webcamsmall.php should also get the same change.

**Comment by steepleian** [comment]
web.php and webcamsmall.php fixed. Variable from settings1.php now being included correctly.
